railsP/config/routes.rb
Rails.application.routes.draw do
  get 'health_record/new'
  get 'health_record/index'

  
  
  get 'comprobantes/new'
  post 'comprobantes/create'
  
  get 'health_record/new'
  post 'health_record/create'
  
  get 'registrations/edit'

  get 'turnos/index'
  
  get 'users/index'
  
  resources :solicitar_turnos
  resources :comprobantes

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'}
  root to: "home#index"
end

railsP/app/models/health_record.rb
class HealthRecord < ApplicationRecord
  belongs_to :user
  validates :dni, presence: true, uniqueness: true
    validates :nombre, presence: true
    validates :apellido, presence: true
    validates :birth, presence: true
    before_save :upcase_content
  
  def upcase_content
      self.nombre=self.nombre.downcase
      self.apellido=self.apellido.downcase
      self.nombre=self.nombre.split(/ |\_/).map(&:capitalize).join(" ")
      self.apellido=self.apellido.split(/ |\_/).map(&:capitalize).join(" ")
  end

end

railsP/app/controllers/health_record_controller.rb
class HealthRecordController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  
  def new
    @record = HealthRecord.new
  end

  def create
    @record = HealthRecord.new(record_params)
    @record.user_id=current_user.id
    @turno = TurnoNoAsignado.new(lugar: "Cementerio", vacuna: "Primer dosis covid", user_id: current_user.id,fecha: DateTime.now.strftime("%d/%m/%Y %H:%M:%S"))
    if @record.save
      flash[:notice] = "Tus datos personales fueron cargados exitosamente! Por favor, carga los datos de tus vacunas previas"
      redirect_to new_comprobante_path
      @turno.save
    else
      render :new
    end
  end

  private
  def record_params
    params.require(:health_record).permit(:dni, :nombre, :apellido,:risk,:birth)
  end

end

railsP/app/helpers/health_record_helper.rb
module HealthRecordHelper
end

railsP/app/views/health_record/index.html.erb
<h1>HealthRecord#index</h1>
<p>Find me in app/views/health_record/index.html.erb</p>

railsP/app/views/health_record/new.html.erb
<h1>Información Personal</h1>

<%=form_for @record, url: health_record_create_path, method: :create do |f|%>

    <div>
        <%= f.text_area :nombre, placeholder:"Nombre", class:'form-control' %>
    </div>
<br/>
    <div>
        <%= f.text_area :apellido, placeholder:"Apellido", class:'form-control' %>
    </div>
<br/>
    <div>
        <%= f.number_field :dni, placeholder:"DNI", class:'form-control' %>
    </div>
<br/>
    <div>
        <%= f.label "Soy paciente de riesgo:"%>
        <%= f.check_box :risk %>
    </div>
<br/>
    <div>
        <%= f.label "Fecha de nacimiento:"%>
        <%= f.date_field :birth, class: 'form-control' %> 
    </div>
<br/>
    <div>
        <%=f.submit 'Siguiente' %>
    </div>
<%end%>