railsP/config/routes.rb
Rails.application.routes.draw do
  get 'health_record/new'
  get 'health_record/index'

  
  
  get 'comprobantes/new'
  post 'comprobantes/create'
  
  get 'health_record/new'
  post 'health_record/create'
  
  get 'registrations/edit'

  get 'turnos/index'
  
  get 'users/index'
  
  resources :solicitar_turnos
  resources :comprobantes

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'}
  root to: "home#index"
end

railsP/app/models/comprobante.rb
class Comprobante < ApplicationRecord
    belongs_to :user
    enum vacuna: {
        covid1:0,
        covid2:1,
        gripe:2,
        fiebre:3
    }
    def humanize
        case self.vacuna
        when 'covid1'
            return "Primera dosis COVID 19"
        when 'covid2'
            return "Segunda dosis COVID 19"
        when 'gripe'
            return "Vacuna antigripal"
        when 'fiebre'
            return "Vacuna contra la fiebre amarilla"
        end
    end
end

railsP/app/controllers/comprobantes_controller.rb
class ComprobantesController < ApplicationController
  before_action :set_comprobante, only: %i[ show edit update destroy ]

  # GET /comprobantes or /comprobantes.json
  def index
    @u = current_user
    @comprobantes = Comprobante.all.where(user_id:@u.id,printable:true)
    #get usuario current role

    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: "comprobantes/comp.pdf.erb", pdf: "Comprobante_#{current_user.health_record.dni}" }
    end
  end

  # GET /comprobantes/1 or /comprobantes/1.json
  def show
    @datos=current_user.health_record
    respond_to do |format|
      format.html
      format.json
      format.pdf{ 
        render pdf: "Comprobante_#{current_user.health_record.dni}",
        template: "comprobantes/comp.pdf.erb"  # Excluding ".pdf" extension.
      }
    end
  end

  # GET /comprobantes/new
  def new
    @comprobante = Comprobante.new
    @u=current_user
    @comprobantes = Comprobante.all.where(user_id:@u.id,printable:false)
  end

  # GET /comprobantes/1/edit
  def edit
  end

  # POST /comprobantes or /comprobantes.json
  def create
    @comprobante = Comprobante.new(comprobante_params)
    @usuario = current_user
    @turno=TurnoNoAsignado.where(:user_id =>@usuario.id)
    if @usuario.role == "Paciente"
      @comprobante.printable = false
      @comprobante.user_id = @usuario.id
    else
      @comprobante.printable = true
    end
    respond_to do |format|
      if !current_user.comprobantes.where(:vacuna =>@comprobante.vacuna).blank?
        format.html{ redirect_to new_comprobante_path, notice: 'Usted ya tiene esta vacuna asignada' }
      elsif @comprobante.vacuna == "covid2" && current_user.comprobantes.where(:vacuna =>0).blank?
        format.html{ redirect_to new_comprobante_path, notice: 'Usted no puede tener la segunda dosis sin antes la primera!!' }
      elsif @comprobante.save
        if @comprobante.vacuna == "covid1"
          @turno.destroy_all
          @turno = TurnoNoAsignado.new(lugar: "Cementerio", vacuna: "Segunda dosis covid", user_id: current_user.id,fecha: DateTime.now.strftime("%d/%m/%Y %H:%M:%S"))
          @turno.save
        elsif @comprobante.vacuna == "covid2"
          @turno.destroy_all
        end
        if current_user.role == "Paciente"
          format.html { redirect_to new_comprobante_path, notice: "Vacuna previa agregada a sus datos" }
        else
          format.html { redirect_to comprobantes_url, notice: "Comprobante was successfully destroyed." }
          format.json { head :no_content }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comprobante.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /comprobantes/1 or /comprobantes/1.json
  def update
    respond_to do |format|
      if @comprobante.update(comprobante_params)
        if current_user.role == "Paciente"
          format.html { redirect_to edit_user_registration_path, notice: "Vacuna editada" }
        else
          format.html { redirect_to comprobantes_url, notice: "Comprobante was successfully destroyed." }
          format.json { head :no_content }
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comprobante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comprobantes/1 or /comprobantes/1.json
  def destroy
    @comprobante.destroy
    @usuario = current_user
    @turno=TurnoNoAsignado.where(:user_id =>@usuario.id)
    if @comprobante.vacuna == "covid1"
      @turno.destroy_all
      @turno = TurnoNoAsignado.new(lugar: "Cementerio", vacuna: "Primera dosis covid", user_id: current_user.id,fecha: DateTime.now.strftime("%d/%m/%Y %H:%M:%S"))
      @turno.save
    elsif @comprobante.vacuna == "covid2"
      @turno.destroy_all
      @turno = TurnoNoAsignado.new(lugar: "Cementerio", vacuna: "Segunda dosis covid", user_id: current_user.id,fecha: DateTime.now.strftime("%d/%m/%Y %H:%M:%S"))
      @turno.save
    end
    respond_to do |format|
      if current_user.role == "Paciente"
        format.html { redirect_to new_comprobante_path, notice: "Vacuna borrada" }
      else
        format.html { redirect_to comprobantes_url, notice: "Comprobante was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comprobante
      @comprobante = Comprobante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comprobante_params
      params.require(:comprobante).permit(:vacuna, :fecha, :descripcion, :observaciones, :user_id)
    end
end

railsP/app/helpers/comprobantes_helper.rb
module ComprobantesHelper
end

railsP/app/views/comprobantes/_form.html.erb
<%= form_with(model: comprobante) do |form| %>
  <% if comprobante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comprobante.errors.count, "error") %> prohibited this comprobante from being saved:</h2>

      <ul>
        <% comprobante.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vacuna %>
    <%= form.select :vacuna, options_for_select([['Primera dosis COVID 19', 'covid1'], ['Segunda Dosis COVID 19', 'covid2'], ['Vacuna antigripal', 'gripe'], ['Vacuna contra la fiebre amarilla', 'fiebre']]), id: :vacuna %>
  </div>

  <!-- <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id%>
  </div> -->

  <div class="field">
    <%= form.label :user_id %>
    <%= form.select :user_id, User.where(role: 'Paciente').map {|u| [u.health_record.nombre,u.id]},{}, { class: 'form-control'} %>
  </div>
  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="field">
    <%= form.label :observaciones %>
    <%= form.text_area :observaciones %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

railsP/app/views/comprobantes/_formPaciente.html.erb
<%= form_with(model: comprobante) do |form| %>
  <% if comprobante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comprobante.errors.count, "error") %> prohibited this comprobante from being saved:</h2>

      <ul>
        <% comprobante.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="field">
    <%= form.label :vacuna %>
    <%= form.select :vacuna, options_for_select([['Primera dosis COVID 19', 'covid1'], ['Segunda Dosis COVID 19', 'covid2'], ['Vacuna antigripal', 'gripe'], ['Vacuna contra la fiebre amarilla', 'fiebre']]), id: :vacuna %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha %>
  </div>

  <div class="actions">
    <%= form.submit 'Agregar vacuna',class:"btn btn-success" %>
  </div>
<% end %>
<h2>Vacunas previas</h2>
<div class="table-responsive">
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th >Vacuna</th>
        <th>Fecha</th>
        <th colspan="3">Acciones</th> 
      </tr>
    </thead>

    <tbody>
      <% @comprobantes.each do |c| %>
        <tr>
            <td><%= c.humanize %></td>
            <td><%= c.fecha %></td>
            <td>
              <%= link_to 'Borrar' , c, method: :delete, data: { confirm: '¿Está seguro?' },class:"btn btn-danger" %>
            </td>
        </tr>
      <% end %>
      <tr>
        <td colspan="4">
          <%= link_to 'Finalizar registro', turnos_index_path, class:"btn btn-success" %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

railsP/app/views/comprobantes/comp.pdf.erb
<p id="notice"><%= notice %></p>
<style>
h1 {text-align: center;font-size: 50;}
h2 {font-size: 25;}
h3 {font-size: 20;color:gray};
</style>
<title>
Comprobante de <%= current_user.health_record.nombre + " " + current_user.health_record.apellido%>
</title>
<body>
  <h1 style=background-color:#96ce7a;color:white;text-decoration: underline;>
    <br/>
    VacunAssist<br/>
    <img width="100" height="100" src="https://i.imgur.com/QQfBKET.png">
    <br/>
  </h1>
  
  <h1>Comprobante</h1>
  <hr class="solid">

  <h2>Vacuna Aplicada:</h2>
  <h3><%= @comprobante.humanize %></h3>
    
  <h2>ID del paciente:</h2>
  <h3><%= @comprobante.user_id%></h3>

  <h2>Nombre:</h2>
  <h3><%= @datos.nombre %><h3>    
  
  <h2>Apellido:</h2>
  <h3><%= @datos.apellido %><h3>    

  <h2>Fecha:</h2>
  <h3><%= @comprobante.fecha %><h3>    

  <h2>Descripcion:</h2>
  <h3><%= @comprobante.descripcion %></h3>    
  
  <h2>Observaciones:</h2>
  <h3><%= @comprobante.observaciones %></h3>    

</body>
  

railsP/app/views/comprobantes/edit.html.erb
<h1>Editing Comprobante</h1>

<%if current_user.role=="Paciente"%>
    <%=render 'formPaciente',comprobante: @comprobante%>
<%else%>
    <%=render 'form',comprobante: @comprobante%>
<%end%>

<%= link_to 'Show', @comprobante %> |
<%= link_to 'Back', comprobantes_path %>

railsP/app/views/comprobantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comprobantes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Vacuna</th>
      <th>Fecha</th>
      <th>Descripcion</th>
      <th>Observaciones</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @comprobantes.each do |c| %>
      <tr>
          <td><%= c.humanize %></td>
          <td><%= c.fecha %></td>
          <td><%= c.descripcion %></td>
          <td><%= c.observaciones %></td>
          <td><%= link_to 'Descargar',comprobante_path(c, format: :pdf) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

railsP/app/views/comprobantes/new.html.erb
<h1>Agregar vacunas</h1>
<%if current_user.role=="Paciente"%>
    <%=render 'formPaciente',comprobante: @comprobante%>
<%else%>
    <%=render 'form',comprobante: @comprobante%>
<%end%>

railsP/app/views/comprobantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vacuna:</strong>
  <%= @comprobante.vacuna %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @comprobante.fecha %>
</p>

<% if @comprobante.printable == true %> 

  <p>
    <strong>Descripcion:</strong>
    <%= @comprobante.descripcion %>
  </p>

  <p>
    <strong>Observaciones:</strong>
    <%= @comprobante.observaciones %>
  </p>

  <%= link_to 'Descargar',comprobante_path(@comprobante, format: :pdf) %>|
<% end %>
<%= link_to 'Inicio', root_path,class:"btn btn-primary"%>
<%= link_to 'Editar', edit_comprobante_path(@comprobante) ,class:"btn btn-info"%> 
<% if current_user.role== 'Paciente'%>
  <%=link_to 'Agregar mas vacunas' , new_comprobante_path,class:"btn btn-success" %>
<% end %>