railsP/config/routes.rb
Rails.application.routes.draw do
  get 'health_record/new'
  get 'health_record/index'

  
  
  get 'comprobantes/new'
  post 'comprobantes/create'
  
  get 'health_record/new'
  post 'health_record/create'
  
  get 'registrations/edit'

  get 'turnos/index'
  
  get 'users/index'
  
  resources :solicitar_turnos
  resources :comprobantes

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'}
  root to: "home#index"
end

railsP/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

railsP/app/models/comprobante.rb
class Comprobante < ApplicationRecord
    belongs_to :user
    enum vacuna: {
        covid1:0,
        covid2:1,
        gripe:2,
        fiebre:3
    }
    def humanize
        case self.vacuna
        when 'covid1'
            return "Primera dosis COVID 19"
        when 'covid2'
            return "Segunda dosis COVID 19"
        when 'gripe'
            return "Vacuna antigripal"
        when 'fiebre'
            return "Vacuna contra la fiebre amarilla"
        end
    end
end

railsP/app/models/health_record.rb
class HealthRecord < ApplicationRecord
  belongs_to :user
  validates :dni, presence: true, uniqueness: true
    validates :nombre, presence: true
    validates :apellido, presence: true
    validates :birth, presence: true
    before_save :upcase_content
  
  def upcase_content
      self.nombre=self.nombre.downcase
      self.apellido=self.apellido.downcase
      self.nombre=self.nombre.split(/ |\_/).map(&:capitalize).join(" ")
      self.apellido=self.apellido.split(/ |\_/).map(&:capitalize).join(" ")
  end

end

railsP/app/models/personal_record.rb
class PersonalRecord < ApplicationRecord
    belongs_to :user
    validates :dni, presence: true, uniqueness: true
    validates :nombre, presence: true
    validates :apellido, presence: true
    before_save :upcase_content

    def upcase_content
        self.nombre=self.nombre.downcase
        self.apellido=self.apellido.downcase
        self.nombre=self.nombre.split(/ |\_/).map(&:capitalize).join(" ")
        self.apellido=self.apellido.split(/ |\_/).map(&:capitalize).join(" ")
    end
end

railsP/app/models/turno_asignado.rb
class TurnoAsignado < ApplicationRecord
    belongs_to :user
end

railsP/app/models/turno_no_asignado.rb
class TurnoNoAsignado < ApplicationRecord
    belongs_to :user
end

railsP/app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:token,:email]
  has_many :comprobantes, :dependent => :destroy
  has_one :personal_record, :dependent => :destroy
  has_one :health_record, :dependent => :destroy
  has_many :TurnoAsignado, :dependent => :destroy 
  has_many :TurnoNoAsignado, :dependent => :destroy
end

railsP/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

railsP/app/controllers/turnos_controller.rb
class TurnosController < ApplicationController
  
  def index
    @turnoNoAsignado = User.find(current_user.id).TurnoNoAsignado
    @turnoAsignado = User.find(current_user.id).TurnoAsignado
    if(User.find(current_user.id).TurnoNoAsignado.count == 0) && (User.find(current_user.id).TurnoAsignado.count == 0)
      flash.now.notice = "No existen solicitudes de turnos y tampoco turnos asignados"
    else
      if(User.find(current_user.id).TurnoAsignado.count == 0)
        flash.now.notice = "No existen turnos asignados"
      else
          if (User.find(current_user.id).TurnoNoAsignado.count == 0)
            flash.now.notice = "No existen solicitudes de turnos"
          end
      end
    end
  end
end

railsP/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

railsP/app/helpers/application_helper.rb
module ApplicationHelper
end

railsP/app/helpers/comprobantes_helper.rb
module ComprobantesHelper
end

railsP/app/helpers/health_record_helper.rb
module HealthRecordHelper
end

railsP/app/helpers/home_helper.rb
module HomeHelper
end

railsP/app/helpers/pacientes_helper.rb
module PacientesHelper
end

railsP/app/helpers/personal_record_helper.rb
module PersonalRecordHelper
end

railsP/app/helpers/solicitar_turno_helper.rb
module SolicitarTurnoHelper
end

railsP/app/helpers/turno_helper.rb
module TurnoHelper
end

railsP/app/helpers/turnos_helper.rb
module TurnosHelper
end

railsP/app/helpers/users_helper.rb
module UsersHelper
end

railsP/app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

railsP/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #96ce7a;">
  <div class="container-fluid">

    <a class="navbar-brand" href="#">
      <img src="https://i.imgur.com/QQfBKET.png" alt="Logo de VacunAssist" width="35" height="35" class="d-inline-block align-text-top">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Inicio",root_path, class:"nav-link"%>
        </li>
        <% if user_signed_in?%>
          <%if current_user.role=="Paciente"%>
          <!-- Paciente -->
            <li class="nav-item"> <%= link_to "Solicitar turnos",new_solicitar_turno_path, class:"nav-link"%></li>
            <li class="nav-item"><%= link_to "Ver mis turnos",turnos_index_path, class:"nav-link"%></li> 
            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <% if current_user.health_record.nil?%>
                  <%= current_user.email%>
                <%else%>  
                  <%= current_user.health_record.nombre %>
                <%end%>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "Ver mis datos",edit_user_registration_path, class:"dropdown-item"%></li>
                <li><%= link_to "Cerrar sesión",destroy_user_session_path, method: :delete, class:"dropdown-item"%></li>
                <li><%= link_to "Ver mis comprobantes",comprobantes_path,class:"dropdown-item"%></li>
              </ul>
            </li>
          <%elsif current_user.role=="Vacunador"%>
            <!--Vacunador -->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.email %></a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "Mi Cuenta",edit_user_registration_path, class:"dropdown-item"%></li>
                <li><%= link_to "Cerrar Sesión",destroy_user_session_path, method: :delete, class:"dropdown-item"%></li>
              </ul>
            </li>
            <li class="nav-item">
              <%= link_to "Turnos",turnos_index_path, class:"nav-link"%>
            </li> 
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <% if current_user.health_record.nil?%>
                <%= current_user.email%>
              <%else%>  
                <%= current_user.health_record.nombre %>
              <%end%>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "Mi Cuenta",edit_user_registration_path, class:"dropdown-item"%></li>
              <li><%= link_to "Cerrar Sesión",destroy_user_session_path, method: :delete, class:"dropdown-item"%></li>
              <li><%= link_to "Comprobantes",comprobantes_path,class:"dropdown-item"%></li>
            </ul>
          <%elsif current_user.role=="Admin"%>
            <!--Admin -->
            <li class="nav-item">
              <%= link_to "Turnos",turnos_index_path, class:"nav-link"%>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%if current_user.health_record.nil?%>
                  <%= current_user.email %>
                <%else%>
                  <%= current_user.health_record.nombre %>
                <%end%>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "Mi Cuenta",edit_user_registration_path, class:"dropdown-item"%></li>
                <li><%= link_to "Cerrar Sesión",destroy_user_session_path, method: :delete, class:"dropdown-item"%></li>
              </ul>
            </li>
            <li class="nav-item">
              <%= link_to "Turnos",turnos_index_path, class:"nav-link"%>
            </li> 
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.health_record.nombre %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "Mi Cuenta",edit_user_registration_path, class:"dropdown-item"%></li>
              <li><%= link_to "Cerrar Sesión",destroy_user_session_path, method: :delete, class:"dropdown-item"%></li>
              <li><%= link_to "Comprobantes",comprobantes_path,class:"dropdown-item"%></li>
            </ul>
        <%end%>
        <% else %>
          <!-- no inicio sesion -->
          <li class="nav-item">
            <%= link_to "Registrarse",new_user_registration_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Iniciar Sesión",new_user_session_path, class:"nav-link"%>
          </li>  
        <% end %>
      </ul>
    </div>
  </div>
</nav>

railsP/app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= value %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

railsP/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>VacunAssist v1.0</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <!-- sistema de alertas al usuario, lo necesita devise -->
      <br/>
      <%= render 'layouts/messages' %>
      <!--<% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>-->
      <%= yield %>
        
    </div>
    <!-- cosas de bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>